/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rohit3DAsset (https://sketchfab.com/Rohit3Dasset)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-ship-32a084f156bf47aca7ba7c21fecfca93
Title: Space Ship
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mascot(props) {
    const { nodes, materials } = useGLTF("/space_ship.glb");
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={10.444}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere3_Drone_0.geometry}
                        material={materials.Drone}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCylinder4_Drone_0.geometry}
                        material={materials.Drone}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface5_Drone_0.geometry}
                        material={materials.Drone}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface6_Drone_0.geometry}
                        material={materials.Drone}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface7_Drone_0.geometry}
                        material={materials.Drone}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface3_Drone_0.geometry}
                        material={materials.Drone}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCylinder3_Drone_0.geometry}
                        material={materials.Drone}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCylinder5_Drone_0.geometry}
                        material={materials.Drone}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/space_ship.glb");
