import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/navigation/header";

const rosnoc = localFont({
    src: "./fonts/rosnoc.woff2",
    variable: "--font-rosnoc",
    display: "swap",
});

const satoshi = localFont({
    src: "./fonts/satoshi.woff2",
    variable: "--font-satoshi",
    display: "swap",
});

export const metadata: Metadata = {
    title: "AEROGUARD",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${rosnoc.variable} ${satoshi.variable} antialiased`}
        >
            <body className="font-satoshi bg-sky-50">
                <Header/>
                {children}
            </body>
        </html>
    );
}
